name: Docker CI
on:
  push:
    tags:
      - "*"
jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Install Redrun
        run: bun i redrun -g --no-save
      - name: NPM Install
        run: bun i --no-save
      - name: Lint
        run: redrun lint
      - name: Build
        id: build
        run: |
          redrun build
          echo "::set-output name=version::$(grep '"version":' package.json -m1 | cut -d\" -f4)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            coderaiser/cloudcmd:latest
            coderaiser/cloudcmd:${{ steps.build.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.build.outputs.version }}
      - name: Build and push alpine-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            coderaiser/cloudcmd:latest-alpine
            coderaiser/cloudcmd:${{ steps.build.outputs.version }}-alpine
            ghcr.io/${{ github.repository }}:latest-alpine
            ghcr.io/${{ github.repository }}:${{ steps.build.outputs.version }}-alpine
